version: 2

project_name: pocketbase

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build_noncgo
    main: ./examples/base
    binary: pocketbase
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/pocketbase/pocketbase.Version={{ .Version }}
      - -X github.com/pocketbase/pocketbase.BuildCommit={{ .ShortCommit }}
      - -X github.com/pocketbase/pocketbase.BuildTime={{ .Date }}
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64, arm]
  goarm: ["7"]

release:
  draft: true

archives:
  - id: archive_noncgo
    builds: [build_noncgo]
    format: zip
    files:
      - LICENSE.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'
      - '^ui:'
