version: 2

project_name: pocketbase

before:
  hooks:
    - go mod tidy

builds:
  - id: pocketbase_noncgo
    main: ./examples/base
    binary: pocketbase
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/pocketbase/pocketbase.Version={{ .Version }}
      - -X github.com/pocketbase/pocketbase.BuildCommit={{ .ShortCommit }}
      - -X github.com/pocketbase/pocketbase.BuildTime={{ .Date }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64

archives:
  - id: pocketbase_noncgo_archive
    builds:
      - pocketbase_noncgo
    format: zip
    files:
      - LICENSE.md
      - CHANGELOG.md

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'
      - '^ui:'
